// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Account struct {
	Id           int64  `json:"id"`
	CreatedAt    string `json:"created_at,optional"` // 用 string 表达时间
	UpdatedAt    string `json:"updated_at,optional"`
	DeletedAt    string `json:"deleted_at,optional"`
	Address      string `json:"address"`
	AddressIndex string `json:"address_index"`
	Comment      string `json:"comment,optional"`
}

type CreateAccountReq struct {
	Address      string `json:"address"`
	AddressIndex string `json:"address_index"`
	Comment      string `json:"comment,optional"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UpdateAccountReq struct {
	Id           int64  `json:"id"`
	Address      string `json:"address,optional"`
	AddressIndex string `json:"address_index,optional"`
	Comment      string `json:"comment,optional"`
}
