// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"go-zero-api-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/accounts",
				Handler: CreateAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/accounts",
				Handler: ListAccountsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/accounts/:id",
				Handler: GetAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/accounts/:id",
				Handler: UpdateAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/accounts/:id",
				Handler: DeleteAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
		},
	)
}
